### ISSUE TITLE
Backend App API URI is not configurable 

### ISSUE THREAD

**Issue by harryttd** [baking-bad/bcdhub#965]
Hi there :)

The sandbox Dockerfile for BCD GUI copies a .env file inside itself and builds the application: https://github.com/baking-bad/bcdhub/blob/e63c562e273462bf0d139b2be42f9d1be6c9b628/build/sandbox/Dockerfile#L9-L11

This file consists of:
https://github.com/baking-bad/bcdhub/blob/e63c562e273462bf0d139b2be42f9d1be6c9b628/build/sandbox/env.production#L1-L3

These are env vars and should be configurable. It seems to me, once they are copied in and `yarn build` is run, they are not configurable anymore. I am trying to deploy the GUI for a private chain but `VUE_APP_API_URI` always targets `localhost:14000` and hence I cannot target my backend.

Would greatly appreciate if this could be addressed. This issue is preventing BCD from being fully self-hosteable.

**Comment by itkach** [comment]
would be great if app loaded it's config at runtime from a relative URL like `./config.json`, then it's easy to drop in a static file, of even just assumed api is served at something like ./api from the same host which is easy enough to implement with a reverse proxy/ingress

**Comment by m-kus** [comment]
In Vue env variables are build-time rather than runtime, that's why they are hardcoded. There are two alternatives if you'd like to change api endpoint:
1. Build bcd front from sources providing your custom env file
2. Create a docker container with hot-reload (non-production) mode, where you can forward any build variables via env vars

We use the second approach for testing sometimes, it is slower that the production build, but flexible.

**Comment by harryttd** [comment]
Thanks for taking at look at the issue. There seems to be some solutions to the way Vue handles this. I can try and play around and create a PR if nobody else has time.

Is there a solution that would be most preferable to what is suggested?
https://stackoverflow.com/questions/53010064/pass-environment-variable-into-a-vue-app-at-runtime
https://moreillon.medium.com/environment-variables-for-containerized-vue-js-applications-f0aa943cb962

**Comment by harryttd** [comment]
I was about to close out this issue showing the solution i used, and just saw this issue is linked to PR #958! This is how i did it:

```shell
set -ex

# The `{{ }}` is Helm templating
api_url="{{ $indexerConfig.gui.apiUrl }}/v1"

for file in js/*; do
  echo $file
  sed -i -E \
    "s~http://localhost:14000/v1~$api_url~g; s~process\.env.VUE_APP_API_URI~\"$api_url\"~g" \
    "$file"
done

/docker-entrypoint.sh nginx -g "daemon off;"
```

It is sufficient for our current use case. Our  k8s pod that is running the api and indexer containers also runs the gui container if configured to do so. This script is run before nginx is run, overwriting the env vars that are hardcoded due to them being provided at build time.

I will leave this issue opened to be closed via PR #958

**Comment by harryttd** [comment]
I forgot to mention, I also needed to update the sandbox.yaml configuration file. There is no shell on the indexer and api images for me to manipulate the file, so I had to create a file and mount it to the location that the sandbox.yaml file lives.
I needed to update the rpc url that the frontend needs to hit:
```yaml
...
    api:
      project_name: api
      bind: ":14000"
      swagger_host: "localhost:8000"
      cors_enabled: true
      sentry_enabled: false
      seed_enabled: true
      page_size: ${PAGE_SIZE:-10}
      frontend:
        ga_enabled: false
        mempool_enabled: false
        sandbox_mode: true
        rpc:
          sandboxnet: {{ $indexerConfig.gui.rpcUrl | default "" }}
...
```
